### ISSUE TITLE
Question: Support for C368 and C388

### ISSUE THREAD

**Issue by okonet** [abaretta/nu.baretta.nad#1]
Hey!

I’m wondering how the interaction with c338 is happening and if there is a possibility to add support for C368 and 388. 

Thanks!

**Comment by abaretta** [comment]
Have you tried the c338 app on the c368/388? The interaction is completely different from the D7050, but possibly/probably similar to the c338.

I developed the app without having access to an actual c338, based on some existing code and feedback from the user. 

You can telnet to the amp, enter commands and get a response. If you can do that manually I could have a look at creating a driver for the device.

**Comment by okonet** [comment]
I think that’s not possible since they aren’t connected to the network. M10 can be a different story though.

**Comment by abaretta** [comment]
Ah, those amps use bluetooth?

In that case support will not be possible based on the existing app.

For amps with an ethernet port it’s worth checking out the interface by connecting with telnet.

Aan za, aug. 31, 2019 om 08:23, Andrey Okonetchnikov <notifications@github.com> schreef:

**Comment by okonet** [comment]
Any pointers for Bluetooth controllers? Is this even possible to reverse engineer their protocol?

**Comment by abaretta** [comment]
No idea, never looked into it. I only have a D7050 myself.

Homey’s bluetooth support is rudimentary at best, I wish whoever is going to take that on all the best 😬

Aan za, aug. 31, 2019 om 10:43, Andrey Okonetchnikov <notifications@github.com> schreef:

**Comment by okonet** [comment]
😂 good to know! I don’t own Homey yet. Considering atm. Is it worth the money?

**Comment by abaretta** [comment]
I think Homey has a lot going for it, but also some weaker points... It depends on what you want to do, and what’s important to you. For me it’s worth it.

The ‘flow’ logic (IF trigger AND/OR condition THEN action) is outstanding in my opinion.

The mobile app is fine, and with things like homekit integration (and Google, Alexa and the other privacy nightmare integrations I dislike but other users are crazy for) you have many options for controlling your devices.

The community is awesome, providing excellent support and great apps. Also worth mentioning, Athom is very security and privacy minded.

On the flipside there are problems with Z-wave (FLIRS is not supported), Zigbee (needs complete rewrite) and bluetooth (rudimentary implementation as mentioned). Oh, and infrared has never really worked properly...

Stability is not as it should be due to a pesky memory leak that affects some users (myself included 😑) and which requires a scheduled reboot every other day...

The issues mentioned are not a big deal for the majority of users. Development is limited by the size of the Athom team, and the businessmodel I guess (only income is the sale of Homeys). This means progress is steady but slow...

The community forum ([https://community.athom.com/](http://community.athom.com/)) and slack channels (https://athomcommunity.slack.com) are the best places to go for info, and of course the app store (https://apps.athom.com) to see which devices are supported.

My 2 cents 😉

Aan za, aug. 31, 2019 om 11:11, Andrey Okonetchnikov <notifications@github.com> schreef:
